version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: authDatabaseContainer
    ports:
      - '6500:5432'
    volumes:
      - progresDB:/data/postgres
    env_file:
      - ./app.env

  pgAdmin:
    image: dpage/pgadmin4
    container_name: pgAdminPR
    env_file:
      - ./app.env
    ports:
      - "5050:80"

  your_server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"  # Порты сервера
    depends_on:
      - postgres
    volumes:
      - ./config/local.yaml:/app/config/local.yaml  # Конфиг

volumes:
  progresDB:
